format = '''$time$git_branch$git_status$kubernetes$python$rust$golang$nodejs$username@$hostname$directory
$cmd_duration\$ '''
scan_timeout = 1000

[time]
disabled = false
time_format = '%F %T'
format = '[\[$time\]]($style) '
style = 'bold bg:120 fg:black'

[kubernetes]
disabled = false
format = '[$symbol$namespace@$context]($style) '

[gcloud]
disabled = true

[username]
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false

[directory]
truncate_to_repo = false
truncation_length = 8

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'bold fg:4'

[nodejs]
format = '[$symbol($version )]($style)'

[cmd_duration]
min_time = 0
min_time_to_notify = 10_000
format = 'took [$duration]($style) '
show_notifications = true
